
# PT
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-pt.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GEN/PT/test_in_GT/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GEN/PT/test_in_GT/log_wer_text_text_pred_gender_wer.csv >  ../../../../results_paper/Human_vs_Generated/GEN/PT/test_in_GT/results_external_by_gender.txt &
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-pt.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GEN/PT/test_in_GEN/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GEN/PT/test_in_GEN/log_wer_text_text_pred_gender_wer.csv >  ../../../../results_paper/Human_vs_Generated/GEN/PT/test_in_GEN/results_external_by_gender.txt &

nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-pt.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/PT/test_in_GT/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/PT/test_in_GT/log_wer_text_text_pred_gender_wer.csv >  ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/PT/test_in_GT/results_external_by_gender.txt &
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-pt.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/PT/test_in_GEN/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/PT/test_in_GEN/log_wer_text_text_pred_gender_wer.csv >  ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/PT/test_in_GEN/results_external_by_gender.txt &

nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-pt.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GT/PT/test_in_GT/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GT/PT/test_in_GT/log_wer_text_text_pred_gender_wer.csv >  ../../../../results_paper/Human_vs_Generated/GT/PT/test_in_GT/results_external_by_gender.txt &
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-pt.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GT/PT/test_in_GEN/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GT/PT/test_in_GEN/log_wer_text_text_pred_gender_wer.csv >  ../../../../results_paper/Human_vs_Generated/GT/PT/test_in_GEN/results_external_by_gender.txt &

nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-pt.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/PT/test_in_GT/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/PT/test_in_GT/log_wer_text_text_pred_gender_wer.csv >  ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/PT/test_in_GT/results_external_by_gender.txt &
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-pt.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/PT/test_in_GEN/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/PT/test_in_GEN/log_wer_text_text_pred_gender_wer.csv >  ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/PT/test_in_GEN/results_external_by_gender.txt &


# RU

nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-ru.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GEN/RU/test_in_GT/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GEN/RU/test_in_GT/log_wer_text_text_pred_gender_wer.csv --russian >  ../../../../results_paper/Human_vs_Generated/GEN/RU/test_in_GT/results_external_by_gender.txt &
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-ru.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GEN/RU/test_in_GEN/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GEN/RU/test_in_GEN/log_wer_text_text_pred_gender_wer.csv --russian >  ../../../../results_paper/Human_vs_Generated/GEN/RU/test_in_GEN/results_external_by_gender.txt &

nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-ru.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/RU/test_in_GT/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/RU/test_in_GT/log_wer_text_text_pred_gender_wer.csv --russian >  ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/RU/test_in_GT/results_external_by_gender.txt &
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-ru.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/RU/test_in_GEN/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/RU/test_in_GEN/log_wer_text_text_pred_gender_wer.csv --russian >  ../../../../results_paper/Human_vs_Generated/GEN-with-DA-PS/RU/test_in_GEN/results_external_by_gender.txt &

nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-ru.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GT/RU/test_in_GT/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GT/RU/test_in_GT/log_wer_text_text_pred_gender_wer.csv --russian >  ../../../../results_paper/Human_vs_Generated/GT/RU/test_in_GT/results_external_by_gender.txt &
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-ru.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GT/RU/test_in_GEN/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GT/RU/test_in_GEN/log_wer_text_text_pred_gender_wer.csv --russian >  ../../../../results_paper/Human_vs_Generated/GT/RU/test_in_GEN/results_external_by_gender.txt &

nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-ru.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/RU/test_in_GT/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/RU/test_in_GT/log_wer_text_text_pred_gender_wer.csv --russian >  ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/RU/test_in_GT/results_external_by_gender.txt &
nohup python3 compute_metrics.py --dataset_csv ../../../../results_paper/test-common_voice-ru.tsv --transcription_csv ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/RU/test_in_GEN/transcription.csv  --output_file  ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/RU/test_in_GEN/log_wer_text_text_pred_gender_wer.csv --russian >  ../../../../results_paper/Human_vs_Generated/GT_with_DA_PS/RU/test_in_GEN/results_external_by_gender.txt &

